In [30]:
import numpy as np

import pandas as pd

import matplotlib.pyplot as plt

import seaborn as sns



In [31]:
from sklearn.model_selection import train_test_split

In [32]:
from sklearn.neighbors import KNeighborsClassifier

In [36]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [37]:






from sklearn.model_selection import cross_val_score

from sklearn import datasets

In [43]:
dataset = pd. read_csv(r'D:\yoges\weka\Weka-3-9-6\data\Iris.csv') #only here change the address in which ur file is stored
#Summarize the Dataset

print ('dataset shape is :', dataset.shape)
print ('dataset head :', dataset.head (5))

print ('dataset description :', dataset.describe() )

dataset.groupby('class').size()

#Dividing data into features and labels

feature_columns = ['sepallength', 'sepalwidth', 'petallength', 'petalwidth']

X = dataset[feature_columns].values

y = dataset['class'].values



dataset shape is : (150, 5)
dataset head :    sepallength  sepalwidth  petallength  petalwidth        class
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa
dataset description :        sepallength  sepalwidth  petallength  petalwidth
count   150.000000  150.000000   150.000000  150.000000
mean      5.843333    3.054000     3.758667    1.198667
std       0.828066    0.433594     1.764420    0.763161
min       4.300000    2.000000     1.000000    0.100000
25%       5.100000    2.800000     1.600000    0.300000
50%       5.800000    3.000000     4.350000    1.300000
75%       6.400000    3.300000     5.100000    1.800000
max       7.900000    4.400000     6.900000    2.500000


In [44]:
#Spliting dataset into training set and test set

X_train, X_test, y_train, y_test= train_test_split(X, y, test_size = 0.2, random_state = 0) 

# Instantiate learning model (k = 3) 
classifier = KNeighborsClassifier(n_neighbors=5)

# Fitting the model 
classifier.fit (X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

cm = confusion_matrix(y_test, y_pred)
print ('confusion matrix: \n', cm)

accuracy = accuracy_score(y_test, y_pred)*100

print ('Accuracy of our model is equal ' ,str(round(accuracy, 2)) ,'%.')

confusion matrix: 
 [[11  0  0]
 [ 0 12  1]
 [ 0  0  6]]
Accuracy of our model is equal  96.67 %.
